# $Id: makefile,v 1.30 2003/04/28 21:21:08 nscollins Exp $ 

LOCDIR   = src/Infrastructure

include $(ESMF_DIR)/makefile

DIRS     = Base IO LogErr TimeMgmt Machine TimeMgr CommMem \
	   ConfigAttr PerfProf Data Route DistGrid PhysGrid Grid Field \
           mpiuni

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =



