# $Id: makefile,v 1.43 2003/10/07 22:33:37 nscollins Exp $ 

LOCDIR   = src/Infrastructure

include $(ESMF_DIR)/makefile

DIRS     =	Base IO LogErr TimeMgmt Machine TimeMgr LocalArray DataMap \
		DELayout Config PerfProf Array DistGrid PhysGrid Grid Route \
		ArrayComm Field Bundle Regrid mpiuni
CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =



