# $Id: makefile,v 1.53 2004/03/17 21:38:27 nscollins Exp $ 

LOCDIR   = src/Infrastructure

include $(ESMF_DIR)/makefile

DIRS     =	Base IO Machine TimeMgr ArraySpec LocalArray DataMap \
		DELayout Config PerfProf Array DistGrid PhysGrid Grid Route \
		ArrayComm Field Bundle Regrid FieldComm BundleComm VM \
		newDELayout LogErr mpiuni 
CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =



