# $Id: makefile,v 1.1 2007/06/12 04:54:24 cdeluca Exp $

all: demos

LOCDIR   = src/demos/coupled_flow

include $(ESMF_DIR)/makefile

DIRS     = src doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
