# $Id: makefile,v 1.8 2006/01/30 20:10:09 nscollins Exp $

ALL:  build_examples

run: run_examples

CFLAGS    =
FFLAGS    =
SOURCEC	  = 
SOURCEF	  = 
SOURCEH	  = 
OBJSC     = 
OBJSF     = 
TEXFILES  = 

LOCDIR	  = src/Infrastructure/PhysGrid/examples

EXAMPLES_BUILD =

EXAMPLES_RUN     = 

EXAMPLES_RUN_UNI = 


include $(ESMF_DIR)/makefile

DIRS	  = 

CLEANDIRS   = 
CLEANFILES  = $(EXAMPLES_BUILD)
CLOBBERDIRS =







