# $Id$ 

ALL: build_here

LOCDIR   = src/prologue

include $(ESMF_DIR)/makefile

DIRS     = tests

ifeq ($(ESMF_YAMLCPP),internal)
DIRS     += yaml-cpp
endif

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =



