# $Id: makefile,v 1.1 2011/01/25 05:08:19 theurich Exp $ 

ALL: tree_build_apps

LOCDIR	  = src/apps/ESMF_WebServController


APPS_BUILD        = $(ESMF_APPSDIR)/ESMF_WebServController
APPS_MAINLANGUAGE = C

APPS_OBJ      = ESMF_WebServController.o

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  = $(APPS_BUILD)
CLOBBERDIRS =

