# $Id: makefile,v 1.1 2004/03/17 04:56:31 cdeluca Exp $

ALL: build_here

CFLAGS    =
FFLAGS    =
SOURCEC   = 
SOURCEF   =
STOREH    = ESMC_IO.h

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))

MANSEC    = IOobj
LIBBASE   = libesmf
DIRS      =
LOCDIR    = src/Infrastructure/IO/src

include $(ESMF_DIR)/makefile

DIRS =

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
