# $Id: makefile,v 1.3 2008/09/26 05:53:54 cdeluca Exp $

ALL: build_here

SOURCEC   = 
SOURCEF   = ESMF_IOSpec.F90
STOREH    = 

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))

LIBBASE   = libesmf
LOCDIR    = src/Infrastructure/IOSpec/src

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =

include $(ESMF_DIR)/makefile

DIRS =
