# $Id: makefile,v 1.14 2007/08/21 02:27:45 cdeluca Exp $

ALL:  build_examples

run: run_examples

CFLAGS    =
FFLAGS    =
SOURCEC	  = 
SOURCEF	  =

SOURCEH	  = 
OBJSC	  =  
OBJSF	  = 
MANSEC	  = 
LIBBASE	  = 
LOCDIR	  = src/Infrastructure/Route/examples

EXAMPLES_BUILD   = 

EXAMPLES_RUN     = 

EXAMPLES_RUN_UNI = 


include ${ESMF_DIR}/makefile

DIRS =


CLEANDIRS   = 
CLEANFILES  = $(EXAMPLES_BUILD)
CLOBBERDIRS =


#
# ESMF_RouteEx
#
run_ESMF_RouteEx:

run_ESMF_RouteEx_uni:


