name: netcdf_hdf5_no_pnetcdf_ncint_mpich
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CPPFLAGS: "-I/home/runner/mpich/include -I/home/runner/hdf5/include -I/home/runner/netcdf-c/include -I/home/runner/netcdf-fortran/include"
      LDFLAGS: "-L/home/runner/mpich/lib -L/home/runner/hdf5/lib -L/home/runner/netcdf-c/lib -L/home/runner/netcdf-fortran/lib"
      # Note issue https://github.com/NCAR/ParallelIO/issues/1889 netcdf integration currently only works with netcdf 4.7.4
      NETCDF_C_VERSION: 4.7.4
      NETCDF_F_VERSION: 4.5.4
      MPICH_VERSION: 4.0.3
      HDF5_VERSION_MAJOR: 1.12
      HDF5_VERSION_PATCH: 2
      FFLAGS: "-fallow-argument-mismatch"
      FCFLAGS: "-fallow-argument-mismatch"
    steps:
    - uses: actions/checkout@v3
    - name: Installs
      run: |
        sudo apt-get install doxygen graphviz wget gfortran libjpeg-dev libz-dev
    - name: cache-mpich
      id: cache-mpich
      uses: actions/cache@v3
      with:
        path: ~/mpich
        key: mpich-${{ runner.os }}-${{ env.MPICH_VERSION }}

    - name: build-mpich
      if: steps.cache-mpich.outputs.cache-hit != 'true'
      run: |
        wget http://www.mpich.org/static/downloads/${{ env.MPICH_VERSION }}/mpich-${{ env.MPICH_VERSION }}.tar.gz &> /dev/null
        tar -xzf mpich-${{ env.MPICH_VERSION }}.tar.gz
        pushd mpich-${{ env.MPICH_VERSION }}
        ./configure --prefix=/home/runner/mpich
        make
        sudo make install
        popd
    - name: cache-hdf5
      id: cache-hdf5
      uses: actions/cache@v3
      with:
        path: ~/hdf5
        key: hdf5-${{ runner.os }}-${{ env.HDF5_VERSION_MAJOR }}.${{ env.HDF5_VERSION_PATCH }}-mpich-${{ env.MPICH_VERSION }}

    - name: build-hdf5
      if: steps.cache-hdf5.outputs.cache-hit != 'true'
      run: |
        set -x
        export PATH="/home/runner/mpich/bin:$PATH"
        export CC=/home/runner/mpich/bin/mpicc
        wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-${{ env.HDF5_VERSION_MAJOR }}/hdf5-${{ env.HDF5_VERSION_MAJOR }}.${{ env.HDF5_VERSION_PATCH }}/src/hdf5-${{ env.HDF5_VERSION_MAJOR }}.${{ env.HDF5_VERSION_PATCH }}.tar.gz &> /dev/null
        tar -xzf hdf5-${{ env.HDF5_VERSION_MAJOR }}.${{ env.HDF5_VERSION_PATCH }}.tar.gz
        pushd hdf5-${{ env.HDF5_VERSION_MAJOR }}.${{ env.HDF5_VERSION_PATCH }}
        ./configure --prefix=/home/runner/hdf5 --enable-parallel --disable-tools --disable-fortran --disable-cxx --enable-parallel-tests
        make
        sudo make install
        popd
    - name: cache-netcdf-c
      id: cache-netcdf-c
      uses: actions/cache@v3
      with:
        path: ~/netcdf-c
        key: netcdf-c-${{ runner.os }}-${{ env.NETCDF_C_VERSION }}-mpich-${{ env.MPICH_VERSION }}-hdf5-${{ env.HDF5_VERSION_MAJOR }}.${{ env.HDF5_VERSION_PATCH }}

    - name: build-netcdf-c
      if: steps.cache-netcdf-c.outputs.cache-hit != 'true'
      run: |
        set -x
        export PATH="/home/runner/mpich/bin:$PATH"
        export CC=/home/runner/mpich/bin/mpicc
        wget https://github.com/Unidata/netcdf-c/archive/refs/tags/v${{ env.NETCDF_C_VERSION }}.tar.gz
        tar -xzf v${{ env.NETCDF_C_VERSION }}.tar.gz &> /dev/null
        pushd netcdf-c-${{ env.NETCDF_C_VERSION }}
        ./configure --prefix=/home/runner/netcdf-c --disable-dap --disable-utilities
        make -j
        sudo make install
        popd

    - name: cache-netcdf-fortran
      id: cache-netcdf-fortran
      uses: actions/cache@v3
      with:
        path: ~/netcdf-fortran
        key: netcdf-fortran-${{ runner.os }}-${{ env.NETCDF_F_VERSION }}-mpich-${{ env.MPICH_VERSION }}-hdf5-${{ env.HDF5_VERSION_MAJOR }}.${{ env.HDF5_VERSION_PATCH }}

    - name: build-netcdf-fortran
      if: steps.cache-netcdf-fortran.outputs.cache-hit != 'true'
      run: |
        set -x
        export PATH="/home/runner/mpich/bin:$PATH"
        export CC=/home/runner/mpich/bin/mpicc
        wget https://github.com/Unidata/netcdf-fortran/archive/refs/tags/v${{ env.NETCDF_F_VERSION }}.tar.gz
        tar -zxf v${{ env.NETCDF_F_VERSION }}.tar.gz &> /dev/null
        pushd netcdf-fortran-${{ env.NETCDF_F_VERSION }}
        ./configure --prefix=/home/runner/netcdf-fortran
        make -j
        sudo make install
        popd

    - name: autotools build
      run: |
        set -x
        gcc --version
        export PATH=/home/runner/mpich/bin:/home/runner/netcdf-c/bin:$PATH
        export CC=/home/runner/mpich/bin/mpicc
        export FC=/home/runner/mpich/bin/mpifort
        autoreconf -i
        ./configure --enable-fortran --enable-netcdf-integration --disable-pnetcdf
        make -j check
        
        
