# $Id: makefile,v 1.1 2010/09/01 23:40:26 peggyli Exp $ 

ALL: tree_build_apps

LOCDIR	  = src/apps/RegridWeightGen


APPS_BUILD    = $(ESMF_APPSDIR)/ESMF_RegridWeightGen

APPS_OBJ      = ESMF_RegridWeightGen.o

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  = $(APPS_BUILD)
CLOBBERDIRS =
