# $Id$ 

ALL: tree_build_apps 

LOCDIR	  = src/apps/ESMF_RegridWeightGen

APPS_BUILD    = $(ESMF_APPSDIR)/ESMF_RegridWeightGen

APPS_OBJ      = ESMF_RegridWeightGen.o

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  = $(APPS_BUILD)
CLOBBERDIRS =
