# $Id: makefile,v 1.4 2007/12/13 17:14:47 feiliu Exp $ 

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/ArraySpec/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src interface examples tests doc 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


