# $Id: makefile,v 1.3 2004/06/09 08:37:33 nscollins Exp $ 

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/ArraySpec/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src interface examples doc 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


