# $Id: makefile,v 1.1 2004/03/17 18:23:28 nscollins Exp $ 

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/ArraySpec/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src interface doc 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


