#if 0
$Id: ESMF_Macros.inc,v 1.2 2003/09/09 20:07:31 nscollins Exp $

Earth System Modeling Framework
Copyright 2002-2003, University Corporation for Atmospheric Research,
Massachusetts Institute of Technology, Geophysical Fluid Dynamics
Laboratory, University of Michigan, National Centers for Environmental
Prediction, Los Alamos National Laboratory, Argonne National Laboratory,
NASA Goddard Space Flight Center.
Licensed under the GPL.

Do not have C++ or F90 style comments in here because this file is processed
by both C++ and F90 compilers.

These lines prevent this file from being read more than once if it
ends up being included multiple times.
#endif

#ifndef ESMF_MACROS_INC
#define ESMF_MACROS_INC

#if 0

former file contents moved to ESMF_BaseMod
so user code can be compiled without requiring
the preprocessor.

#endif 

#if 0
i left the following macro here for our own internal use.
#endif

#define ESMF_SRCLINE __FILE__, __LINE__

#endif 
