# $Id: makefile,v 1.4 2003/09/17 20:15:36 flanigan Exp $

LOCDIR    = src/Infrastructure/LogErr/

include $(ESMF_DIR)/makefile

DIRS      = interface src doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
