# $Id: makefile,v 1.1 2003/03/28 23:04:12 nscollins Exp $

LOCDIR    = src/Infrastructure/LogErr/

include $(ESMF_DIR)/makefile

DIRS      = doc
#DIRS      = src interface examples doc
#DIRS      = src interface examples tests doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
