# $Id: makefile,v 1.3 2003/04/15 20:21:31 nscollins Exp $

LOCDIR    = src/Infrastructure/LogErr/

include $(ESMF_DIR)/makefile

#DIRS      = doc
DIRS      = interface src examples doc
#DIRS      = src interface examples tests doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
