# $Id: makefile,v 1.1 2008/04/24 21:30:00 rokuingh Exp $ 

ALL: build_here 

SOURCEC	  = 
SOURCEF	  = ESMF_Attribute.F90
SOURCEH	  = 

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))

MANSEC	  = Attrobj
LIBBASE	  = libesmf
DIRS	  = 
LOCDIR	  = src/Superstructure/Attribute_API/interface

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =






