# $Id: makefile,v 1.2 2004/03/18 16:24:43 nscollins Exp $ 

ALL: build_here 

CFLAGS    =
FFLAGS    =
SOURCEC	  = ESMC_IOSpec.C
SOURCEF	  = 
SOURCEH	  = 
STOREH    = ESMC_IOSpec.h

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))
MANSEC	  = IOSpecobj
LIBBASE	  = libesmf
DIRS	  = 
LOCDIR	  = src/Infrastructure/IOSpec/interface

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =




