# $Id$ 

ALL: tree_build_apps 

LOCDIR	  = src/apps/ESMF_Scrip2Unstruct

APPS_BUILD    = $(ESMF_APPSDIR)/ESMF_Scrip2Unstruct
APPS_MAINLANGUAGE = C

APPS_OBJ      = ESMF_Scrip2Unstruct.o

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  = $(APPS_BUILD)
CLOBBERDIRS =


