# $Id: makefile,v 1.14 2007/07/19 04:14:26 oehmke Exp $

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/Grid/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = doc src interface tests examples

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
