# $Id: makefile.tests,v 1.3 2003/03/06 18:52:52 flanigan Exp $

ALL:  tests

CFLAGS    =
FFLAGS    =
SOURCEC	  = 
SOURCEF	  =

SOURCEH	  = 
OBJSC	  =  
OBJSF	  = 
MANSEC	  = 
LIBBASE	  = 
LOCDIR	  = src/Infrastructure/<Comp>/tests

TESTS_BUILD   = $(ESMC_TESTDIR)/ESMF_<Class>UTest \
	        $(ESMC_TESTDIR)/ESMC_<Class>UTest 

TESTS_RUN     = RUN_ESMF_<Class>UTest \
		RUN_ESMC_<Class>UTest 

TESTS_RUN_UNI = RUN_ESMF_<Class>UTestUNI \
		RUN_ESMC_<Class>UTESTUNI 

TESTS_RM      = ESMF_<Class>UTest.rm \
                ESMC_<Class>UTest.rm


include ${ESMF_DIR}/makefile

DIRS	  = 

$(ESMC_TESTDIR)/ESMF_<Class>UTest: chkopts ESMF_<Class>UTest.o
	-${F90CXXLD} -o $(ESMC_TESTDIR)/ESMF_<Class>UTest ESMF_<Class>UTest.o -lesmf ${F90CXXLIBS} ${MPI_LIB} ${MP_LIB} ${THREAD_LIB} ${PCL_LIB}
	${RM} ESMF_<Class>UTest.o

RUN_ESMF_<Class>UTest:
	-@rm -f testlog stdlog.* logfile.* ESMF_<Class>UTest.tmps
	${MPIRUN} -np 4 $(ESMC_TESTDIR)/ESMF_<Class>UTest > $(ESMC_TESTDIR)/ESMF_<Class>UTest.stdout

RUN_ESMF_<Class>UTestUNI:
	-@rm -f testlog stdlog.* logfile.* ESMF_<Class>UTest.tmps
	${MPIRUN} -np 1 $(ESMC_TESTDIR)/ESMF_<Class>UTest > $(ESMC_TESTDIR)/ESMF_<Class>UTest.stdout

ESMF_<Class>UTest.rm:
	echo "ESMF_<Class>Test.rm target called here."


$(ESMC_TESTDIR)/ESMC_<Class>UTest: chkopts ESMC_<Class>UTest.o
	-${F90CXXLD} -o $(ESMC_TESTDIR)/ESMC_<Class>UTest ESMC_<Class>UTest.o -lesmf ${F90CXXLIBS} ${MPI_LIB} ${MP_LIB} ${THREAD_LIB} ${PCL_LIB}
	${RM} ESMC_<Class>UTest.o

RUN_ESMF_<Class>UTest:
	-@rm -f testlog stdlog.* logfile.* ESMC_<Class>UTest.tmps
	${MPIRUN} -np 4 $(ESMC_TESTDIR)/ESMC_<Class>UTest > $(ESMC_TESTDIR)/ESMC_<Class>UTest.stdout

RUN_ESMF_<Class>UTestUNI:
	-@rm -f testlog stdlog.* logfile.* ESMF_<Class>UTest.tmps
	${MPIRUN} -np 1 $(ESMC_TESTDIR)/ESMC_<Class>UTest > $(ESMC_TESTDIR)/ESMC_<Class>UTest.stdout

ESMC_<Class>UTest.rm:
	echo "ESMC_<Class>Test.rm target called here."



