# $Id: makefile,v 1.3.10.1 2008/04/16 17:30:32 theurich Exp $

ALL: build_here

LOCDIR   = src/Infrastructure/stubs

include $(ESMF_DIR)/makefile


DIRS     =	mpiuni

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =

