# $Id: makefile,v 1.3 2004/06/08 10:34:53 nscollins Exp $

ALL: build_here

LOCDIR   = src/Infrastructure/stubs

include $(ESMF_DIR)/makefile


DIRS     =	mpiuni netcdf_stubs hdf_stubs

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =



