# $Id: makefile,v 1.2 2004/06/08 09:27:21 nscollins Exp $

ALL: build_here

LOCDIR   = src/Infrastructure/stubs

include $(ESMF_DIR)/makefile


#DIRS     =	mpiuni netcdf_stubs hdf_stubs
DIRS     =	mpiuni

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =



