#!/bin/csh -f
#
#-------------------------------------------------------------------------------
# Runs Tex files through LaTex and latex2html to create Postscript
# and *.html files that you can examine.
#===============================================================================
# CVS $Id$
#===============================================================================
# Updates version of the ESMF Software Developer's Guide:
#
# - runs latex compiler and builds .dvi file 
# - builds html file using latex2html
# - builds postscript file and compresses it
# - copies postscript file to CGD ftp site.
#
# $Id$
#
# History:
#    C. DeLuca 4/19/01
#-------------------------------------------------------------------------------

latex dev_guide.tex
latex dev_guide.tex
./dotoc dev_guide
bibtex dev_guide
latex dev_guide.tex
bibtex dev_guide
latex dev_guide.tex

latex2html -white \
	   -toc_depth 5 \
           -split 4 \
	   -local_icons \
           -show_section_numbers \
           -address "<A HREF="mailto:esmf_support@list.woc.noaa.gov">esmf_support@list.woc.noaa.gov</A>" dev_guide.tex


rm -rf dev_guide/TMP
dvips -o dev_guide.ps dev_guide.dvi
dvipdf dev_guide.dvi




