# $Id: makefile,v 1.1 2004/06/04 15:48:02 nscollins Exp $

ALL: build_here 

CFLAGS    =
FFLAGS    =

SOURCEC	  = 
SOURCEF	  = 
SOURCEH	  = 

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))

MANSEC	  = hdf
LIBBASE	  = libhdf_stubs

LOCDIR	  = src/Infrastructure/stubs/hdf_stubs/

include $(ESMF_DIR)/makefile

DIRS	  = 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =






