# $Id: makefile,v 1.1 2008/04/24 21:30:00 rokuingh Exp $

ALL: build_here

# this needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Superstructure/Attribute_API/

# leave this line alone.
include ${ESMF_DIR}/makefile


# the DIRS line needs to contain all subdirectories which exist 
#  directly below this directory, and have either library,
#  example/test code, or documents which need to be generated.
DIRS	  = interface tests doc




