labels: ["source: discussions", "product: ESMPy"]
body:
  - type: markdown
    attributes:
      value: |
        ### Instructions
        Before submitting a new discussion please review the [ESMPy Documentation](https://earthsystemmodeling.org/esmpy/) and check for [existing discussions](https://github.com/orgs/esmf-org/discussions?discussions_q=).
       
        **Note:** The ESMF Core Team continues to operate the esmf_support@ucar.edu address. If you have privacy concerns posting to ESMF Discussions or if you prefer email then send us an email.
  - type: checkboxes
    attributes:
      label: Requirements
      options:
        - label: Reviewed [ESMPy Documentation](https://earthsystemmodeling.org/esmpy/)
          required: true
        - label: Searched [GitHub Discussions](https://github.com/orgs/esmf-org/discussions?discussions_q=)
          required: true
  - type: input
    id: affiliation
    attributes:
      label: Affiliation(s)
      description: "Are you affiliated with an organization?"
      placeholder: "NASA, NOAA, NRL, NSF-NCAR, University, ..."
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: ESMF Version
      description: "What version of ESMF are you using?"
      placeholder: "v0.0.0"
    validations:
      required: false
  - type: textarea
    id: question
    attributes:
      label: Issue
      description: "What is your question or issue?"
      placeholder: "enter issue here"
    validations:
      required: true
  - type: dropdown
    id: tag
    attributes:
      label: Autotag
      options:
        - "@billsacks"
      default: 0
    validations:
      required: true
