# $Id: makefile,v 1.3 2008/09/26 04:17:32 cdeluca Exp $ 

ALL:  build_examples

run: run_examples

LOCDIR	  = src/Infrastructure/Util/examples

EXAMPLES_BUILD = 

EXAMPLES_RUN = 

EXAMPLES_RUN_UNI = 


include $(ESMF_DIR)/makefile

DIRS	  = 

CLEANDIRS   = 
CLEANFILES  = $(EXAMPLES_BUILD)
CLOBBERDIRS =


