# $Id: makefile,v 1.1.2.2 2010/03/10 06:33:08 oehmke Exp $

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/GeomBase

# Leave this line alone.
include ${ESMF_DIR}/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src interface

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


