# $Id: makefile,v 1.1 2004/07/28 19:38:51 nscollins Exp $

all: build_release

LOCDIR   = src/release/include

# destdir is relative to the release directory
RELEASE_DESTDIR = include
RELEASE_COPYFILES = $(ESMF_INCDIR)/\*
RELEASE_ARCHCOPYFILES = 

include $(ESMF_DIR)/makefile

DIRS     = 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
