# $Id: makefile,v 1.2 2008/09/26 04:17:23 cdeluca Exp $

ALL: build_examples

run: run_examples

LOCDIR	  = src/Infrastructure/InternDG/examples


EXAMPLES_BUILD   = 

EXAMPLES_RUN     =

EXAMPLES_RUN_UNI = 


include $(ESMF_DIR)/makefile

DIRS	  = 

CLEANDIRS   = 
CLEANFILES  = $(EXAMPLES_BUILD)
CLOBBERDIRS =



#
#  Run targets
#




