# $Id: makefile,v 1.19 2010/11/03 04:58:52 theurich Exp $ 

ALL: build_here

LOCDIR   = src/Superstructure

include $(ESMF_DIR)/makefile

DIRS     =  State Component AttributeAPI IOAPI ESMFMod AppDriver

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =










