# $Id$ 

ALL: build_here

LOCDIR   = src/Superstructure

include $(ESMF_DIR)/makefile

DIRS     =  State Component AttachMethods AttributeAPI WebServices PreESMFMod ESMFMod AppDriver

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =










