# $Id: makefile,v 1.1 2003/09/18 13:34:32 cdeluca Exp $ 


LOCDIR	  = src/Infrastructure/DataMap/

include $(ESMF_DIR)/makefile

DIRS	  = src interface doc 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


