# $Id: makefile,v 1.6 2003/03/25 00:18:17 flanigan Exp $ 
ALL: lib 

CFLAGS    =
FFLAGS    =
SOURCEC	  = 
SOURCEF	  = 
SOURCEH	  = 
OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))
MANSEC	  = Machineobj
LIBBASE	  = libesmf
LOCDIR	  = src/Infrastructure/Machine/

include $(ESMF_DIR)/makefile

DIRS	  = doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =






