# $Id: makefile,v 1.6 2008/09/26 05:18:03 cdeluca Exp $ 

ALL: build_here 

SOURCEC	  = ESMC_Attribute_F.C
SOURCEF	  = 
SOURCEH	  = 

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))

LIBBASE	  = libesmf
LOCDIR	  = src/Infrastructure/Attribute/interface

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =

include $(ESMF_DIR)/makefile

DIRS = 




