# $Id: makefile,v 1.2 2005/02/02 20:57:43 jwolfe Exp $

all: demos

LOCDIR   = src/demo/interacting_flow

include $(ESMF_DIR)/makefile

DIRS     = src doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
