# $Id: makefile,v 1.1.2.1 2005/02/09 17:01:50 nscollins Exp $

all: demos

LOCDIR   = src/demo/interacting_flow

include $(ESMF_DIR)/makefile

DIRS     = src doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
