# $Id: makefile,v 1.1 2004/10/14 17:00:54 nscollins Exp $

all: demo

LOCDIR   = src/demo/interacting_flow

include $(ESMF_DIR)/makefile

DIRS     = src doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
