# $Id: makefile,v 1.2 2002/10/08 19:27:28 nscollins Exp $ 

DIRS	  = src interface
#DIRS	  = src interface examples doc
LOCDIR	  = src/Infrastructure/Base/

include ${ESMF_DIR}/build/${ESMF_ARCH}/base



