# $Id: makefile,v 1.8 2004/03/18 18:34:18 nscollins Exp $ 

ALL:  build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/Base/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src interface doc tests

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =






