# $Id: makefile,v 1.3 2006/03/20 20:13:19 tjcnrl Exp $

ALL: build_here 

CFLAGS    =
FFLAGS    =

SOURCEC	  = 
SOURCEF	  = netcdf_stub.f90
SOURCEH	  = netcdf.inc

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))

MANSEC	  = netcdf
LIBBASE	  = libnetcdf_stubs

LOCDIR	  = src/Infrastructure/stubs/netcdf_stubs/

include $(ESMF_DIR)/makefile

DIRS	  = 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =






