# $Id: makefile,v 1.2 2004/06/07 17:07:19 slswift Exp $

ALL: build_here 

CFLAGS    =
FFLAGS    =

SOURCEC	  = 
SOURCEF	  = netcdf_stub.F
SOURCEH	  = netcdf.inc

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))

MANSEC	  = netcdf
LIBBASE	  = libnetcdf_stubs

LOCDIR	  = src/Infrastructure/stubs/netcdf_stubs/

include $(ESMF_DIR)/makefile

DIRS	  = 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =






