# $Id$ 

ALL: tree_build_apps

LOCDIR	  = src/apps/ESMX_Builder


APPS_BUILD        = $(ESMF_APPSDIR)/ESMX_Builder
APPS_MAINLANGUAGE = script

APPS_OBJ      = ESMX_Builder.sh

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  = $(APPS_BUILD)
CLOBBERDIRS =

