# $Id: makefile,v 1.4.2.1 2005/02/09 17:01:49 nscollins Exp $

all: demos

LOCDIR   = src/demo/coupled_flow

include $(ESMF_DIR)/makefile

DIRS     = src doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
