# $Id: makefile,v 1.2 2003/11/10 22:09:28 nscollins Exp $

all: demo

LOCDIR   = src/demo/coupled_flow

include $(ESMF_DIR)/makefile

DIRS     = src 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
