# $Id: makefile,v 1.4 2003/05/07 06:58:52 cdeluca Exp $

all: demo

LOCDIR   = src/Demo/coupled_flow

include $(ESMF_DIR)/makefile

DIRS     = src doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
