# $Id: makefile,v 1.1 2003/09/18 18:59:30 cdeluca Exp $

all: demo

LOCDIR   = src/demo/coupled_flow

include $(ESMF_DIR)/makefile

DIRS     = src doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
