# $Id: makefile,v 1.8 2008/09/26 05:18:12 cdeluca Exp $

ALL:   build_examples

run: run_examples

LOCDIR	  = src/Superstructure/ESMFMod/examples

EXAMPLES_BUILD =
EXAMPLES_RUN =
EXAMPLES_RUN_UNI =

CLEANDIRS   = 
CLEANFILES  = $(EXAMPLES_BUILD)
CLOBBERDIRS =

include ${ESMF_DIR}/makefile

DIRS = 



