# $Id$

ALL:   build_examples

run: run_examples

LOCDIR	  = src/Superstructure/ESMFMod/examples

EXAMPLES_BUILD =
EXAMPLES_RUN =
EXAMPLES_RUN_UNI =

CLEANDIRS   = 
CLEANFILES  = $(EXAMPLES_BUILD)
CLOBBERDIRS =

include ${ESMF_DIR}/makefile

DIRS = 



