# $Id: makefile,v 1.12 2007/08/17 20:53:26 cdeluca Exp $

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/Regrid/

# Leave this line alone.
include $(ESMF_DIR)/makefile


# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src doc examples

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
