# $Id: makefile,v 1.6 2003/05/07 04:34:31 cdeluca Exp $



# this needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/Regrid/

# leave this line alone.
include $(ESMF_DIR)/makefile


# the DIRS line needs to contain all subdirectories which exist 
#  directly below this directory, and have either library,
#  example/test code, or documents which need to be generated.
DIRS	  = doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
