# $Id: makefile,v 1.1 2010/07/27 05:52:46 theurich Exp $

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Superstructure/WebServices/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =




