version: 2.1

jobs:

  build-esmf:
    machine: true
    resource_class: large
    environment:
      - ESMF_DIR: $CIRCLE_WORKING_DIRECTORY/sandbox/esmf/src-git
      - DOCKER_IMG: bekozi/esmf
      - TEST_RUNNER: esmf-test-runner
    steps:
#      - run:
#          name: passthru-build-esmf
#          command: exit 0
      - run:
          name: Checkout Code
          command: git clone --branch $CIRCLE_BRANCH --depth 1 https://github.com/esmf-org/esmf.git $ESMF_DIR
      - run:
          name: make info
          command: bash $ESMF_DIR/.circleci/sh/make-info.sh
      - run:
          name: make
          command: bash $ESMF_DIR/.circleci/sh/make.sh
      - run:
          name: make install
          command: bash $ESMF_DIR/.circleci/sh/make-install.sh
      - run:
          name: Test Environment Finalize
          command: bash $ESMF_DIR/.circleci/sh/docker-push.sh

  build-run-tests:
    parameters:
      target:
        type: string
    docker:
      - image: bekozi/esmf:$CIRCLE_BRANCH
    resource_class: xlarge
    environment:
      - ESMF_ARTIFACTS: /artifacts
      - ESMF_OUTDIR: /artifacts/test-artifacts
    steps:
#      - run:
#          name: passthru-build-tests
#          command: exit 0
      - run:
          name: Create Artifacts Directory
          command: mkdir -p $ESMF_OUTDIR
      - run:
          name: make build_<< parameters.target >>
          command: cd $ESMF_DIR && make build_<< parameters.target >> 2>&1 | tee $ESMF_OUTDIR/esmf-make-build_<< parameters.target >>.out
      - run:
          name: make run_<< parameters.target >>
          command: cd $ESMF_DIR && make run_<< parameters.target >> 2>&1 | tee $ESMF_OUTDIR/esmf-make-run_<< parameters.target >>.out
      - run:
          name: Collect Artifacts
          command: bash $ESMF_DIR/.circleci/sh/collect-test-artifacts.sh << parameters.target >>
      - store_artifacts:
          path: /artifacts/test-artifacts.zip
          destination: << parameters.target >>-artifacts.zip

  build-docs:
    environment:
      - ESMF_DIR: $CIRCLE_WORKING_DIRECTORY/sandbox/esmf/src-git
      - ESMF_ARTIFACTS: "/artifacts"
      - DOCKER_IMG: bekozi/esmf-doc
    machine: true
    steps:
#      - run:
#          name: passthru-build-docs
#          command: exit 0
      - run:
          name: Checkout Code
          command: git clone --branch $CIRCLE_BRANCH --depth 1 https://github.com/esmf-org/esmf.git $ESMF_DIR
      - run:
          name: Docker Build
          command: docker build -t "${DOCKER_IMG}:${CIRCLE_BRANCH}" --file "${ESMF_DIR}/.circleci/docker/esmf-doc/Dockerfile" --build-arg ESMF_BRANCH="${CIRCLE_BRANCH}" .
      - run:
          name: Extract Artifacts
          command: bash $ESMF_DIR/.circleci/sh/extract-artifacts.sh
      - store_artifacts:
          path: /tmp/doc-artifacts.zip
          destination: doc-artifacts.zip

  publish-docs:
    machine: true
#    docker:
#      - image: bekozi/esmf-doc:$CIRCLE_BRANCH
    steps:
      - run:
          name: passthru-publish-docs
          command: exit 0

  external_demos:
    machine: true
    steps:
      - run:
          name: passthru-external_demos
          command: exit 0

  bit-for-bit:
    machine: true
    steps:
      - run:
          name: passthru-bit-for-bit
          command: exit 0

  esmpy-build:
    machine: true
    steps:
      - run:
          name: passthru-esmpy-build
          command: exit 0

  esmpy-test:
    machine: true
    steps:
      - run:
          name: passthru-esmpy-test
          command: exit 0

  esmpy-docs:
    machine: true
    steps:
      - run:
          name: passthru-esmpy-docs
          command: exit 0

workflows:
  build-and-test:
    jobs:
      - build-esmf
      - build-run-tests:
          name: build-run-<< matrix.target >>
          matrix:
            parameters:
              target: ["unit_tests", "system_tests", "examples"]
          requires:
            - build-esmf
#      - external_demos:
#          name: placeholder-external_demos
#          requires:
#            - build-run-tests
#      - bit-for-bit:
#          name: placeholder-bit-for-bit
#          requires:
#            - build-run-tests
#      - esmpy-build:
#          name: placeholder-esmpy-build
#          requires:
#            - build-esmf
#      - esmpy-test:
#          name: placeholder-esmpy-test
#          requires:
#            - placeholder-esmpy-build

  docs:
    jobs:
      - build-docs
#      - publish-docs:
#          name: placeholder-publish-docs
#          requires:
#            - build-docs
#      - esmpy-docs:
#          name: placeholder-esmpy-docs
