# $Id: makefile,v 1.2 2003/07/09 17:51:10 nscollins Exp $

all: build_release

LOCDIR   = src/release/mod

# destdir is relative to the release directory
RELEASE_DESTDIR = mod
RELEASE_COPYFILES = $(ESMF_MODDIR)/$(ESMF_RELEASE_MOD_FILES)
RELEASE_ARCHCOPYFILES = 

include $(ESMF_DIR)/makefile

DIRS     = 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
