# $Id$ 

ALL: build_here 

SOURCEC	  = esmftrc.c esmftrc_filesys.c esmftrc_f.c
SOURCEF	  = 
SOURCEH	  = esmftrc.h esmftrc_filesys.h esmftrc_f.h
STOREH    = 

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))

LIBBASE	  = libesmf
LOCDIR	  = src/Infrastructure/Trace/src

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =

include $(ESMF_DIR)/makefile

DIRS	  = 


