# $Id$ 

ALL: build_here 

SOURCEC	  = esmftrc.c ESMCI_Trace.C
SOURCEF	  = 
SOURCEH	  = esmftrc.h ESMCI_Trace.h
STOREH    = 

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))

LIBBASE	  = libesmf
LOCDIR	  = src/Infrastructure/Trace/src

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =

include $(ESMF_DIR)/makefile

DIRS	  = 


