# $Id: makefile,v 1.2 2004/01/29 17:11:54 nscollins Exp $

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/VM

# Leave this line alone.
include ${ESMF_DIR}/makefile


# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.

# until there are contents in the subdirectories, these cannot
# be listed here - they break the make system.
DIRS	  =
#DIRS	  = src interface




