# $Id: makefile,v 1.4 2002/10/08 19:10:26 nscollins Exp $ 

DIRS	  = src interface 
#DIRS	  = doc src interface examples 
LOCDIR	  = src/Infrastructure/DistGrid/

include ${ESMF_DIR}/build/${ESMF_ARCH}/base






