# $Id: makefile,v 1.3 2002/10/08 18:45:38 nscollins Exp $ 

DIRS	  = src 
#DIRS	  = doc src interface examples 
LOCDIR	  = src/Infrastructure/DistGrid/

include ${ESMF_DIR}/build/${ESMF_ARCH}/base






