# $Id: makefile,v 1.5 2002/11/01 18:40:27 jwolfe Exp $

# the DIRS line needs to contain all subdirectories which exist 
#  directly below this directory, and have either library,
#  example/test code, or documents which need to be generated.
DIRS	  = src interface examples doc

# this needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/DistGrid/

# leave this line alone.
include ${ESMF_DIR}/build/${ESMF_ARCH}/base



