# $Id: makefile,v 1.2 2003/03/11 01:27:00 cdeluca Exp $

# the DIRS line needs to contain all subdirectories which exist 
#  directly below this directory, and have either library,
#  example/test code, or documents which need to be generated.
DIRS	  = 
# src interface examples doc tests

# this needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/Route/

# leave this line alone.
include ${ESMF_DIR}/makefile



