# $Id: makefile,v 1.11 2005/02/28 16:35:22 nscollins Exp $

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/Route/

# Leave this line alone.
include ${ESMF_DIR}/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src interface examples tests doc
#DIRS	  = src interface examples doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


