# $Id: makefile,v 1.3 2010/09/22 23:46:55 theurich Exp $ 

ALL: build_apps

LOCDIR   = src/apps

include $(ESMF_DIR)/makefile

DIRS      = ESMF_Info ESMF_InfoC ESMF_RegridWeightGen

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =

