# $Id$ 

ALL: build_apps

LOCDIR   = src/apps

include $(ESMF_DIR)/makefile

DIRS      = ESMF_PrintInfo ESMF_PrintInfoC ESMF_RegridWeightGen ESMF_WebServController ESMF_Scrip2Unstruct  ESMF_Regrid

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =

