# $Id: makefile,v 1.4 2011/02/07 18:47:15 gerhard.j.theurich Exp $ 

ALL: build_apps

LOCDIR   = src/apps

include $(ESMF_DIR)/makefile

DIRS      = ESMF_Info ESMF_InfoC ESMF_RegridWeightGen ESMF_WebServController

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =

