# $Id: makefile,v 1.9 2003/04/04 22:42:24 flanigan Exp $

# this needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Superstructure/Component/

# leave this line alone.
include $(ESMF_DIR)/makefile

# the DIRS line needs to contain all subdirectories which exist 
#  directly below this directory, and have either library,
#  example/test code, or documents which need to be generated.
DIRS	  = src interface tests doc
#DIRS	  = src interface examples tests doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =




