# $Id: makefile,v 1.6 2003/03/20 23:31:45 svasquez Exp $


# this needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Superstructure/Component/

# leave this line alone.
include $(ESMF_DIR)/makefile


# the DIRS line needs to contain all subdirectories which exist 
#  directly below this directory, and have either library,
#  example/test code, or documents which need to be generated.
DIRS	  = src interface doc tests
#DIRS	  = src interface examples tests doc



