# $Id: makefile,v 1.1 2003/09/19 17:00:02 cdeluca Exp $

LOCDIR    = src/Infrastructure/DELayout

include $(ESMF_DIR)/makefile

DIRS     = src interface examples doc tests

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
