# $Id: makefile,v 1.4 2008/09/26 21:11:38 cdeluca Exp $ 

ALL: build_here 

SOURCEC	  = mpi.c
SOURCEF	  = 
SOURCEH	  = mpi.h mpif.h

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))

LIBBASE	  = libesmf
LOCDIR	  = src/Infrastructure/stubs/mpiuni

include $(ESMF_DIR)/makefile

DIRS	  = 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =






