# $Id: makefile,v 1.1 2004/06/04 15:48:02 nscollins Exp $ 

ALL: build_here 

CFLAGS    =
FFLAGS    =

SOURCEC	  = mpi.c
SOURCEF	  = 
SOURCEH	  = mpi.h mpif.h

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))

MANSEC	  = Timeobj
LIBBASE	  = libmpiuni

LOCDIR	  = src/Infrastructure/stubs/mpiuni/

include $(ESMF_DIR)/makefile

DIRS	  = 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =






