# $Id: makefile,v 1.1.8.1 2006/09/14 16:32:20 theurich Exp $ 

ALL: build_here 

CFLAGS    =
FFLAGS    =

SOURCEC	  = mpi.c
SOURCEF	  = 
SOURCEH	  = mpi.h mpif.h

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))

MANSEC	  = Timeobj
LIBBASE	  = libesmf

LOCDIR	  = src/Infrastructure/stubs/mpiuni/

include $(ESMF_DIR)/makefile

DIRS	  = 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =






