#!/bin/sh
# $Id: mpirun,v 1.5 2012/06/06 17:51:46 w6ws Exp $

CYCLE=1
while [ $CYCLE = 1 ]
do
    case $1 in
    --help)
	echo "Usage: mpirun [OPTION]... [command [arg ...]]"
	echo "-np 1           run the command with one processor (default)"
	echo "--help          display this help and exit"
	echo "-v, --version   output version information and exit"
	exit 0
	;;

    -np)
	if [ $2 != "1" ]; then
	    echo "FAIL:Uniprocessor version of MPI can only use one processor."
	    exit 1
	fi
	shift; shift
	;;

    --version|-v)
	echo "ESMF mpirun:"
	echo "  revision$Revision: 1.5 $"
	echo "  revision date$Date: 2012/06/06 17:51:46 $"
	echo "  tag$Name:  $"
	exit 0
	;;

    *)
	CYCLE=0;;
    esac
done

if [ $# -gt 0 ]; then
# If relative path is used prepend a ./
    progname=`dirname $1`/`basename $1`
    shift

# Execute the program
    $progname $*
    exit $?
fi

exit 0
