# $Id: makefile,v 1.2 2008/04/02 23:05:29 cdeluca Exp $ 

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/FieldBundle/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src interface doc tests examples

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


