# $Id: makefile,v 1.2 2008/10/09 17:01:02 rokuingh Exp $

ALL: build_here

# this needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Superstructure/AttributeAPI/

# leave this line alone.
include ${ESMF_DIR}/makefile


# the DIRS line needs to contain all subdirectories which exist 
#  directly below this directory, and have either library,
#  example/test code, or documents which need to be generated.
#DIRS	  = interface doc examples
DIRS      = interface tests doc examples





