# $Id: makefile,v 1.1 2004/02/11 18:59:46 theurich Exp $

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/newDELayout

# Leave this line alone.
include ${ESMF_DIR}/makefile


# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.

# until there are contents in the subdirectories, these cannot
# be listed here - they break the make system.
#DIRS	  = src interface
DIRS	= 

