# $Id: makefile,v 1.2 2004/03/18 18:35:25 nscollins Exp $

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/newDELayout

# Leave this line alone.
include ${ESMF_DIR}/makefile


# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.

# until there are contents in the subdirectories, these cannot
# be listed here - they break the make system.
#DIRS	  = src interface
DIRS	= 

