# $Id: makefile,v 1.3 2004/06/11 21:53:42 svasquez Exp $

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/ArrayComm/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src interface doc examples

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
