# $Id: makefile,v 1.1 2010/09/22 23:46:55 theurich Exp $ 

ALL: tree_build_apps

LOCDIR	  = src/apps/ESMF_InfoC


APPS_BUILD        = $(ESMF_APPSDIR)/ESMF_InfoC
APPS_MAINLANGUAGE = C

APPS_OBJ      = ESMF_InfoC.o

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  = $(APPS_BUILD)
CLOBBERDIRS =

