# $Id$ 

ALL: tree_build_apps 

LOCDIR	  = src/apps/ESMF_Regrid

APPS_BUILD    = $(ESMF_APPSDIR)/ESMF_Regrid

APPS_OBJ      = ESMF_Regrid.o

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  = $(APPS_BUILD)
CLOBBERDIRS =
