# $Id: makefile,v 1.2.2.1 2007/12/14 21:12:03 theurich Exp $

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/Mesh/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
