#
#  makefile
#
#  Runs ESMF system tests on IRIX64

ESMF_LIB_DIR = ../lib

# if you move the location of the ESMF library, 
# you must add the new directory name to 
# the LD_LIBRARY64_PATH environment variable. 

run:
	-mpirun -np 4 ./CoupledFlowApp
	@echo "ESMF Demo Application complete.  This directory"
	@echo "should now contain 10 output data dumps, in ascii,"
	@echo "each one consisting of an energy file (SIE), and the"
	@echo "U and V velocity fields."


