#
#  makefile
#
#  Runs ESMF demo on rs6000_64

# if you move the location of the ESMF library, add the
# new directory to the LIBPATH environment variable.

run:
	-export MP_RMPOOL=1 ;\
	export MP_PROCS=4  ;\
	export MP_NODES=1  ;\
	export MP_TASKS_PER_NODE=4 ;\
	poe ./CoupledFlowApp
	@echo "ESMF Demo Application complete.  This directory"
	@echo "should now contain 10 output data dumps, in ascii,"
	@echo "each one consisting of an energy file (SIE), and the"
	@echo "U and V velocity fields."





