#
#  makefile
#
#  Runs ESMF demo on alpha


run:
	@if [ "X${PROJECT_NAME}" = "X" ] ; then \
	  echo "The environment variable PROJECT_NAME must be set." ; fi 
	bsub -P "$(PROJECT_NAME)" -q general -I -n 4  prun -n 4 ./CoupledFlowApp
	@echo "ESMF Demo Application complete.  This directory"
	@echo "should now contain 10 output data dumps, in ascii,"
	@echo "each one consisting of an energy file (SIE), and the"
	@echo "U and V velocity fields."



