# $Id: makefile,v 1.1 2005/05/16 21:48:47 nscollins Exp $

ALL:  build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/Util/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.

# This directory is currently a placeholder for generic utility
# routines which are not part of any particular class; e.g. string
# handling routines, getting time-of-day from the system for a timestamp, etc.
# When code is actually moved here, comment back in the appropropriate 
# subdirs from the list below.
#DIRS	  = src interface doc tests examples
DIRS	  = 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


