#if 0
$Id: ESMF_Conf.inc,v 1.2 2004/11/01 21:20:23 nscollins Exp $

Earth System Modeling Framework
Copyright 2002-2003, University Corporation for Atmospheric Research,
Massachusetts Institute of Technology, Geophysical Fluid Dynamics
Laboratory, University of Michigan, National Centers for Environmental
Prediction, Los Alamos National Laboratory, Argonne National Laboratory,
NASA Goddard Space Flight Center.
Licensed under the GPL.
#endif

#if 0
currently an empty file.  available if #defines needed
on a per-system basis for F90 code
#endif

#if 0
currently in the ESMF_Config.F90 file, if EOL is defined
as achar(10) (newline), the file will not parse.  when
whatever this bug is turns out to be is fixed, this next
define can be removed.
#endif
#define ESMF_HAS_ACHAR_BUG 1

