#include "MOAB_FCDefs.h"
#ifdef MOAB_FC_FUNC_

#define MBCN_GetBasis MOAB_FC_FUNC_( mbcn_getbasis, MBCN_GETBASIS )
#define MBCN_SetBasis MOAB_FC_FUNC_( mbcn_setbasis, MBCN_SETBASIS )
#define MBCN_EntityTypeName MOAB_FC_FUNC_( mbcn_entitytypename, MBCN_ENTITYTYPENAME )
#define MBCN_EntityTypeFromName MOAB_FC_FUNC_( mbcn_entitytypefromname, MBCN_ENTITYTYPEFROMNAME )
#define MBCN_Dimension MOAB_FC_FUNC_( mbcn_dimension, MBCN_DIMENSION )
#define MBCN_VerticesPerEntity MOAB_FC_FUNC_( mbcn_verticesperentity, MBCN_VERTICESPERENTITY )
#define MBCN_NumSubEntities MOAB_FC_FUNC_( mbcn_numsubentities, MBCN_NUMSUBENTITIES )
#define MBCN_SubEntityType MOAB_FC_FUNC_( mbcn_subentitytype, MBCN_SUBENTITYTYPE )
#define MBCN_SubEntityVertexIndices MOAB_FC_FUNC_( mbcn_subentityvertexindices, MBCN_SUBENTITYVERTEXINDICES )
#define MBCN_AdjacentSubEntities MOAB_FC_FUNC_( mbcn_adjacentsubentities, MBCN_ADJACENTSUBENTITIES )
#define MBCN_SideNumberInt MOAB_FC_FUNC_( mbcn_sidenumberint, MBCN_SIDENUMBERINT )
#define MBCN_SideNumberUint MOAB_FC_FUNC_( mbcn_sidenumberuint, MBCN_SIDENUMBERUINT )
#define MBCN_SideNumberLong MOAB_FC_FUNC_( mbcn_sidenumberlong, MBCN_SIDENUMBERLONG )
#define MBCN_SideNumberUlong MOAB_FC_FUNC_( mbcn_sidenumberulong, MBCN_SIDENUMBERULONG )
#define MBCN_SideNumberVoid MOAB_FC_FUNC_( mbcn_sidenumbervoid, MBCN_SIDENUMBERVOID )
#define MBCN_SideNumber MOAB_FC_FUNC_( mbcn_sidenumber, MBCN_SIDENUMBER )
#define MBCN_OppositeSide MOAB_FC_FUNC_( mbcn_oppositeside, MBCN_OPPOSITESIDE )
#define MBCN_ConnectivityMatchInt MOAB_FC_FUNC_( mbcn_connectivitymatchint, MBCN_CONNECTIVITYMATCHINT )
#define MBCN_ConnectivityMatchUint MOAB_FC_FUNC_( mbcn_connectivitymatchuint, MBCN_CONNECTIVITYMATCHUINT )
#define MBCN_ConnectivityMatchLong MOAB_FC_FUNC_( mbcn_connectivitymatchlong, MBCN_CONNECTIVITYMATCHLONG )
#define MBCN_ConnectivityMatchUlong MOAB_FC_FUNC_( mbcn_connectivitymatchulong, MBCN_CONNECTIVITYMATCHULONG )
#define MBCN_ConnectivityMatchVoid MOAB_FC_FUNC_( mbcn_connectivitymatchvoid, MBCN_CONNECTIVITYMATCHVOID )
#define MBCN_setPermutation MOAB_FC_FUNC_( mbcn_setpermutation, MBCN_SETPERMUTATION )
#define MBCN_resetPermutation MOAB_FC_FUNC_( mbcn_resetpermutation, MBCN_RESETPERMUTATION )
#define MBCN_permuteThisInt MOAB_FC_FUNC_( mbcn_permutethisint, MBCN_PERMUTETHISINT )
#define MBCN_permuteThisUint MOAB_FC_FUNC_( mbcn_permutethisuint, MBCN_PERMUTETHISUINT )
#define MBCN_permuteThisLong MOAB_FC_FUNC_( mbcn_permutethislong, MBCN_PERMUTETHISLONG )
#define MBCN_permuteThisVoid MOAB_FC_FUNC_( mbcn_permutethisvoid, MBCN_PERMUTETHISVOID )
#define MBCN_revPermuteThisInt MOAB_FC_FUNC_( mbcn_revpermutethisint, MBCN_REVPERMUTETHISINT )
#define MBCN_revPermuteThisUint MOAB_FC_FUNC_( mbcn_revpermutethisuint, MBCN_REVPERMUTETHISUINT )
#define MBCN_revPermuteThisLong MOAB_FC_FUNC_( mbcn_revpermutethislong, MBCN_REVPERMUTETHISLONG )
#define MBCN_revPermuteThisVoid MOAB_FC_FUNC_( mbcn_revpermutethisvoid, MBCN_REVPERMUTETHISVOID )
#define MBCN_HasMidEdgeNodes MOAB_FC_FUNC_( mbcn_hasmidedgenodes, MBCN_HASMIDEDGENODES )
#define MBCN_HasMidFaceNodes MOAB_FC_FUNC_( mbcn_hasmidfacenodes, MBCN_HASMIDFACENODES )
#define MBCN_HasMidRegionNodes MOAB_FC_FUNC_( mbcn_hasmidregionnodes, MBCN_HASMIDREGIONNODES )
#define MBCN_HasMidNodes MOAB_FC_FUNC_( mbcn_hasmidnodes, MBCN_HASMIDNODES )
#define MBCN_HONodeParent MOAB_FC_FUNC_( mbcn_honodeparent, MBCN_HONODEPARENT )
#define MBCN_HONodeIndex MOAB_FC_FUNC_( mbcn_honodeindex, MBCN_HONODEINDEX )

#endif
