# $Id: makefile,v 1.3 2002/10/08 19:14:15 nscollins Exp $ 

DIRS	  =  interface
#DIRS	  =  src interface examples doc
LOCDIR	  = src/Infrastructure/IO/

include ${ESMF_DIR}/build/${ESMF_ARCH}/base



