# $Id: makefile,v 1.18 2009/07/21 05:56:58 eschwab Exp $ 

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/IO/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS      = src interface tests doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =

