# $Id: makefile,v 1.2 2004/10/14 17:00:53 nscollins Exp $

all: demo

LOCDIR   = src/demo

include $(ESMF_DIR)/makefile

DIRS     = coupled_flow \
	   interacting_flow

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
