# $Id: makefile,v 1.1 2003/09/18 18:33:09 cdeluca Exp $

all: demo

LOCDIR   = src/demo

include $(ESMF_DIR)/makefile

DIRS     = coupled_flow

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
