# $Id: makefile,v 1.1 2003/05/02 19:24:01 nscollins Exp $

all: demo

LOCDIR   = src/Demo

include $(ESMF_DIR)/makefile

DIRS     = coupled_flow

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
