# $Id: makefile,v 1.3 2005/02/02 20:47:55 jwolfe Exp $

all: demos

LOCDIR   = src/demo

include $(ESMF_DIR)/makefile

DIRS     = coupled_flow \
	   interacting_flow

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
