# $Id: makefile,v 1.2 2003/10/22 21:22:22 cdeluca Exp $

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Superstructure/Xform/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src interface examples doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =




