# $Id: makefile,v 1.1 2003/10/22 20:09:41 cdeluca Exp $

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Superstructure/State/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src interface examples tests doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =




