# $Id: makefile,v 1.3 2007/10/31 16:59:04 cdeluca Exp $

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Superstructure/State/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src interface doc
# TODO:FIELDINTEGRATION Restore State tests once FieldCreateNoData works
# tests examples

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =




