#if 0
$Id: ESMF_Conf.inc,v 1.1 2006/03/03 16:15:56 nscollins Exp $

Earth System Modeling Framework
Copyright 2002-2006, University Corporation for Atmospheric Research,
Massachusetts Institute of Technology, Geophysical Fluid Dynamics
Laboratory, University of Michigan, National Centers for Environmental
Prediction, Los Alamos National Laboratory, Argonne National Laboratory,
NASA Goddard Space Flight Center.
Licensed under the GPL.
#endif

#if 0
 // define this if needed.
 // #define ESMF_SEQUENCE_BUG 0
#endif



