#
#  makefile
#
#  This makefile will compile an ESMF Example 
#
#  The source file must be of the form *Ex.F90
#
#  This makefile will only compile and link
#  one example.
#
#  The source code for the example must 
#  exist in one file.
#
#  Compiles for rs6000_sp
#

# Find the name of the example.
APP  = $(word 1,$(basename $(wildcard *Ex.F90)))

# Create the name of the object file.
APPO = $(addsuffix .o,$(APP))

# Dir locations
ESMF_LIB_DIR = ../lib
ESMF_MOD_DIR = ../mod


# Default Acction
all: $(APP)


# run the example, overriding some variables which can interfere
# with a simple single task program.
run: $(APP)
	export MP_RMPOOL=1; \
	export MP_NODES=1; \
	export MP_TASKS_PER_NODE=1; \
	export MP_PROCS=1; \
	./$(APP)


# link the example
$(APP) : $(APPO)
	mpxlf90_r -brtl -L$(ESMF_LIB_DIR) -lC -lesmf $^ -o $@


# compile the example
%.o : %.F90
	mpxlf90_r -qsuffix=f=F90 -I$(ESMF_MOD_DIR) -c -o $@ $<


# Clean target
clean:
	rm -f *.o *.mod $(APP)


#Don't throw away the .o file.
.PRECIOUS : %.o










