# $Id: makefile,v 1.3 2004/06/18 20:59:25 eschwab Exp $ 

ALL: build_release

RELEASE_DESTDIR = example
RELEASE_COPYFILES = ESMF_ClockEx.F90
RELEASE_ARCHCOPYFILES = makefile

LOCDIR	  = src/release/example

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  = 
CLOBBERDIRS =



