# $Id: makefile,v 1.2 2003/07/09 17:51:10 nscollins Exp $ 

ALL: build_release

RELEASE_DESTDIR = example
RELEASE_COPYFILES = ESMF_TimeEx.F90
RELEASE_ARCHCOPYFILES = makefile

LOCDIR	  = src/release/example

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  = 
CLOBBERDIRS =



