# $Id: makefile,v 1.5 2007/04/17 21:25:49 tjcnrl Exp $

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR    = src/Infrastructure/Config

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS      = src interface examples doc tests

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
