ALL: onedoc

LOCDIR = src/Superstructure/InfoAPI/doc

DVIFILES  =
PDFFILES  =
HTMLFILES =

#
# Tex Files to make
#
TEXFILES_TO_MAKE  =

include $(ESMF_DIR)/makefile

DIRS = 
CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =

