# $Id: makefile,v 1.4 2008/09/26 05:18:07 cdeluca Exp $

ALL: build_here 

SOURCEC	  = ESMC_InternDG_F.C
SOURCEF	  = 
SOURCEH	  = 

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))

LIBBASE	  = libesmf
LOCDIR	  = src/Infrastructure/InternDG/interface

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =

include $(ESMF_DIR)/makefile

DIRS	  = 

