# $Id: makefile,v 1.2 2003/07/09 17:51:10 nscollins Exp $ 

ALL: build_release

RELEASE_DESTDIR = CoupledFlowSrc
RELEASE_COPYFILES = 
RELEASE_ARCHCOPYFILES = makefile

LOCDIR	  = src/release/CoupledFlowSrc

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  = 
CLOBBERDIRS =



