#
#  makefile
#
#  This makefile will compile an ESMF Demo
#
#  This makefile will only compile and link
#  one demo program
#
#
#  Compiles for rs6000_sp
#

# Find the name of the example.
APP  = CoupledFlowApp

# Create the name of the object file.
APPO =  FlowArraysMod.o InjectArraysMod.o \
        FlowSolverMod.o InjectorMod.o CouplerMod.o \
        CoupledFlowDemo.o CoupledFlowApp.o

# Dir locations
ESMF_LIB_DIR = ../lib
ESMF_MOD_DIR = ../mod


# Default Acction
all: $(APP)


# run the example
run: $(APP)
	-export MP_RMPOOL=1 ;\
	export MP_PROCS=4 ;\
	export MP_NODES=1 ;\
	export MP_TASKS_PER_NODE=4 ;\
	poe ./$(APP)
	@echo "ESMF Demo Application complete.  This directory"
	@echo "should now contain 10 output data dumps, in ascii,"
	@echo "each one consisting of an energy file (SIE), and the"
	@echo "U and V velocity fields."


# link the example
$(APP) : $(APPO)
	mpxlf90_r -brtl -L$(ESMF_LIB_DIR) -lC -lesmf $^ -o $@


# compile the example
%.o : %.F90
	mpxlf90_r -O -qsuffix=f=F90 -I$(ESMF_MOD_DIR) -c -o $@ $<


# Clean target
clean:
	rm -f *.o *.mod $(APP)


#Don't throw away the .o file.
.PRECIOUS : %.o










