# $Id: makefile,v 1.4 2003/09/17 22:45:35 flanigan Exp $

# makefile template for the examples directory.

ALL: examples

CFLAGS    =
FFLAGS    =
SOURCEC	  = 
SOURCEF	  = 
SOURCEH	  = 
OBJSC     = 
OBJSF     = 
TEXFILES  = 
MANSEC	  = 
LIBBASE	  = 
LOCDIR	  = src/Infrastructure/DistGrid/examples

EXAMPLES_BUILD   = 

EXAMPLES_RUN     =

EXAMPLES_RUN_UNI = 


include $(ESMF_DIR)/makefile

DIRS	  = 

CLEANDIRS   = coredir.*
CLEANFILES  = *.o *.mod *.txt *.stdout NULL core $(EXAMPLES_BUILD)
CLOBBERDIRS =



#
#  Run targets
#




