# $Id$ 

ALL: tree_build_apps

LOCDIR	  = src/apps/ESMF_Info


APPS_BUILD    = $(ESMF_APPSDIR)/ESMF_Info

APPS_OBJ      = ESMF_Info.o

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  = $(APPS_BUILD)
CLOBBERDIRS =
