# $Id: makefile,v 1.2 2003/03/25 00:18:06 flanigan Exp $ 


LOCDIR	  = src/Infrastructure/Field/

include $(ESMF_DIR)/makefile

DIRS	  = src interface examples doc tests

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


