# $Id: makefile,v 1.7 2007/10/08 12:44:05 feiliu Exp $ 

ALL:  build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/Field/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src interface doc tests examples
# TODO:FIELDINTEGRATION Restore Field examples and tests.

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


