# $Id: makefile,v 1.2 2003/11/10 22:35:51 nscollins Exp $ 


LOCDIR   = src/Superstructure/AppDriver

# currently there are no subdirs in the quick_start dir.
QUICKSTART_SUBDIRS = 

# copy all files in this dir up to quick_start dir.
# (you should not have build the example first)
QUICKSTART_COPYDIRS = $(ESMF_DIR)/$(LOCDIR)/seq_pairwise_fdriver_spmd

include $(ESMF_DIR)/makefile

# at the present time do NOT list the subdirs here, because the makefiles
# inside them are not intended to be executed as part of the esmf build.
DIRS     =  

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =










