# $Id: makefile,v 1.1 2003/11/07 15:10:27 nscollins Exp $ 


LOCDIR   = src/Superstructure/AppDriver

include $(ESMF_DIR)/makefile


# at the present time do NOT list the subdirs here, because the makefiles
# inside them are not intended to be executed as part of the esmf build.
DIRS     =  

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =










