#if 0
$Id: ESMF_Conf.inc,v 1.1 2005/02/03 17:50:09 nscollins Exp $

Earth System Modeling Framework
Copyright 2002-2003, University Corporation for Atmospheric Research,
Massachusetts Institute of Technology, Geophysical Fluid Dynamics
Laboratory, University of Michigan, National Centers for Environmental
Prediction, Los Alamos National Laboratory, Argonne National Laboratory,
NASA Goddard Space Flight Center.
Licensed under the GPL.
#endif

#if 0
in theory absoft supports initializers, but in practice with the number
of modules we include, it seems to cause problems when enabled.
#endif

#define ESMF_NO_INITIALIZERS 1


