# $Id: makefile,v 1.4 2003/02/27 17:54:14 flanigan Exp $


# this needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/Data/

# leave this line alone.
include $(ESMF_DIR)/makefile

# the DIRS line needs to contain all subdirectories which exist 
#  directly below this directory, and have either library,
#  example/test code, or documents which need to be generated.
DIRS	  = interface src examples tests doc







