# $Id: makefile,v 1.2 2002/12/07 00:16:08 nscollins Exp $

# the DIRS line needs to contain all subdirectories which exist 
#  directly below this directory, and have either library,
#  example/test code, or documents which need to be generated.
DIRS	  = interface src examples doc

# this needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/Data/

# leave this line alone.
include ${ESMF_DIR}/build/${ESMF_ARCH}/base



