# $Id$ 

ALL: tree_build_apps

LOCDIR	  = src/apps/ESMF_PrintInfoC


APPS_BUILD        = $(ESMF_APPSDIR)/ESMF_PrintInfoC
APPS_MAINLANGUAGE = C

APPS_OBJ      = ESMF_PrintInfoC.o

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  = $(APPS_BUILD)
CLOBBERDIRS =

