# $Id: makefile,v 1.4 2003/03/25 00:18:30 flanigan Exp $ 

ALL: lib 

CFLAGS    =
FFLAGS    =
SOURCEC	  = mpi.c
SOURCEF	  = 
SOURCEH	  = mpi.h mpif.h
OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))
MANSEC	  = Timeobj
LIBBASE	  = libmpiuni
LOCDIR	  = src/Infrastructure/mpiuni/


include $(ESMF_DIR)/makefile

DIRS	  = 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =






