# $Id: makefile,v 1.5 2003/06/23 20:25:14 jwolfe Exp $ 

ALL: lib 

CFLAGS    =
FFLAGS    =
SOURCEC	  = mpi.c
SOURCEF	  = 
SOURCEH	  = mpi.h mpif.h
OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))
MANSEC	  = Timeobj
LIBBASE	  = libmpiuni
LOCDIR	  = src/Infrastructure/mpiuni/


include $(ESMF_TOP_DIR)/makefile

DIRS	  = 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =






