# $Id: makefile,v 1.2 2004/06/07 21:20:17 svasquez Exp $

ALL:   build_here

# this needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/BundleDataMap/

# leave this line alone.
include ${ESMF_DIR}/makefile


# the DIRS line needs to contain all subdirectories which exist 
#  directly below this directory, and have either library,
#  example/test code, or documents which need to be generated.
DIRS	  = src interface examples doc tests




