# $Id: makefile,v 1.21 2003/08/06 22:39:01 nscollins Exp $ 

all: system_tests

LOCDIR   = src/SystemTests

include $(ESMF_DIR)/makefile

DIRS     = 69527 70384 70385 63029 62502 74558 74559 82899
#DIRS     = 62503 79497 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =



# DO NOT DELETE
