# $Id: makefile,v 1.6 2003/02/26 02:00:05 nscollins Exp $ 

#DIRS     = 70384 70385 63029
DIRS     = 70384 63029

LOCDIR   = src/SystemTests

include ${ESMF_DIR}/build/${ESMF_ARCH}/base



# DO NOT DELETE
