# $Id: makefile,v 1.10 2003/03/25 00:18:34 flanigan Exp $ 

LOCDIR   = src/SystemTests

include $(ESMF_DIR)/makefile

DIRS     = 70384 70385 63029 62502

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =



# DO NOT DELETE
