# $Id: makefile,v 1.3 2007/10/01 16:32:36 donstark Exp $

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/test_harness/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
#DIRS	  = doc src
DIRS	  =  src

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
