#!/usr/bin/perl

# Perfrom AR while locking the archive file (in case we are a parallel build)
# 
# Usage: ar_lock <ar command> <archive> <file>

if ($#ARGV != 3) {
  print "Usage:ar_lock <lockfile> <ar command> <archive> <file>\n";
  exit;
}

$lockfile=$ARGV[0];
$ar_command=$ARGV[1];
$archive=$ARGV[2];
$file=$ARGV[3];

open (FILE, "< $lockfile") || die "Can't open $lockfile";
$ret = flock FILE, 2;
if (!$ret) {
  print "error, flock 2 failed!!", "\n";
}

print "AR_LOCK <$lockfile>:<$ar_command> <$archive> <$file>", "\n";
$output=`$ar_command $archive $file`;
print "$output";

flock FILE, 8;
close(FILE);

