#!/bin/sh
# return the ESMF version from Git if available, or empty string otherwise
# test looks for .git directory or .git file (when esmf is a submodule)
if [ -d $ESMF_DIR/.git ] || [ -s $ESMF_DIR/.git ] ; then \
TAG=`git describe --tags 2>&1 | grep -v fatal`
ORIG=`git config --get remote.origin.url 2>&1`
if [ -z "$TAG" ] ; then TAG="no tag found" ; fi
if [ -z "$ORIG" ] ; then ORIG="no origin found" ; fi
case "$ORIG" in
  *"esmf-org/esmf.git"*) echo $TAG ;;
  *) echo $TAG "($ORIG)" ;;
esac
fi
