#if 0
$Id: ESMF_Version.inc,v 1.1.4.3 2007/10/18 02:43:24 cdeluca Exp $

Earth System Modeling Framework
Copyright 2002-2007, University Corporation for Atmospheric Research,
Massachusetts Institute of Technology, Geophysical Fluid Dynamics
Laboratory, University of Michigan, National Centers for Environmental
Prediction, Los Alamos National Laboratory, Argonne National Laboratory,
NASA Goddard Space Flight Center.
Licensed under the University of Illinois-NCSA License.

Do not have C++ or F90 style comments in here because this file is processed
by both C++ and F90 compilers.

These lines prevent this file from being read more than once if it
ends up being included multiple times.
#endif

#ifndef ESMF_VERSION_INC
#define ESMF_VERSION_INC

#if 0
contents moved to ESMF_BaseMod so user code
does not require the preprocessor to compile.
#endif

#endif 
