# $Id: makefile,v 1.4 2008/07/23 20:19:49 dneckels Exp $

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/GridUtil

# Leave this line alone.
include ${ESMF_DIR}/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src interface tests examples doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


