# $Id: makefile,v 1.7 2004/02/20 21:28:58 jwolfe Exp $ 

ALL: build_system_tests

LOCDIR   = src/system_tests

include $(ESMF_DIR)/makefile

# arranged roughly in order of complexity
DIRS     = ESMF_RowReduce \
           ESMF_ArrayRedist \
           ESMF_CompCreate \
           ESMF_FieldHalo \
           ESMF_FieldHaloPer \
           ESMF_FieldRegrid \
           ESMF_SimpleCoupling \
           ESMF_FlowComp \
           ESMF_FlowWithCoupling \
           ESMF_FieldRegridMulti

# new tests not yet ready
#DIRS     = ESMF_CplOnExclDEs

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =



# DO NOT DELETE
