# $Id: makefile,v 1.5 2004/02/13 15:38:43 nscollins Exp $ 

ALL: build_system_tests

LOCDIR   = src/system_tests

include $(ESMF_DIR)/makefile

DIRS     = ESMF_ArrayRedist ESMF_CompCreate ESMF_RowReduce ESMF_FieldHalo \
           ESMF_FieldHaloPer ESMF_FieldRegrid ESMF_FlowComp ESMF_FlowWithCoupling \
           ESMF_SimpleCoupling

#DIRS     = ESMF_CplOnExclDEs 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =



# DO NOT DELETE
