# $Id: makefile,v 1.9 2003/03/25 00:18:28 flanigan Exp $

LOCDIR    = src/Infrastructure/TimeMgr/

include $(ESMF_DIR)/makefile

DIRS      = src interface examples tests doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
