# $Id: makefile,v 1.11 2004/03/18 18:35:41 nscollins Exp $

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR    = src/Infrastructure/TimeMgr/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS      = src interface examples tests doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
