# $Id: makefile,v 1.1 2002/10/08 18:58:02 nscollins Exp $ 

DIRS	  = src interface examples
#DIRS	  = doc src interface examples
LOCDIR	  = src/Infrastructure/TimeMgr/

include ${ESMF_DIR}/build/${ESMF_ARCH}/base





