# $Id: makefile,v 1.3 2004/02/25 17:23:08 cdeluca Exp $


# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/BundleComm/

# Leave this line alone.
include ${ESMF_DIR}/makefile


# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src interface examples doc


