# $Id: makefile,v 1.13 2008/09/26 04:16:42 cdeluca Exp $ 

ALL: build_here 

SOURCEC	  = ESMC_Base_F.C
SOURCEF	  = ESMF_Base.F90 
SOURCEH	  = 

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))

LIBBASE	  = libesmf
DIRS	  = 
LOCDIR	  = src/Infrastructure/Base/interface

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =






