# $Id: makefile,v 1.5 2003/04/03 22:40:27 nscollins Exp $ 


# this needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR    = src/Infrastructure/PerfProf

# leave this line alone.
include $(ESMF_DIR)/makefile

# the DIRS line needs to contain all subdirectories which exist
#  directly below this directory, and have either library,
#  example/test code, or documents which need to be generated.

DIRS     = doc
#DIRS     = src interface examples tests doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


