# $Id: makefile,v 1.7 2007/08/30 05:06:33 cdeluca Exp $

ALL: build_here

# this needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/FieldComm/

# leave this line alone.
include ${ESMF_DIR}/makefile


# the DIRS line needs to contain all subdirectories which exist 
#  directly below this directory, and have either library,
#  example/test code, or documents which need to be generated.
DIRS	  = src interface doc
# TODO:FIELDINTEGRATION Restore FieldComm tests and examples.

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =




