# $Id$ 

ALL: build_here 

AUTOGEN	  =
SOURCEC	  =
SOURCEF	  = ESMF_InfoDescribe.F90 ESMF_InfoSync.F90 ESMF_InfoCache.F90
SOURCEH	  = 
TEXFILES  = $(addsuffix _fapi.tex, $(basename $(AUTOGEN)))

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))

LIBBASE	  = libesmf
LOCDIR	  = src/Superstructure/InfoAPI/interface

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =

include $(ESMF_DIR)/makefile

DIRS = 






