# $Id: makefile,v 1.7 2003/03/25 00:17:46 flanigan Exp $

LOCDIR    = src/Infrastructure/CommMem

include $(ESMF_DIR)/makefile

DIRS     = src interface examples doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
