# $Id: makefile,v 1.10 2003/06/17 19:49:25 jwolfe Exp $

LOCDIR    = src/Infrastructure/CommMem

include $(ESMF_DIR)/makefile

DIRS     = src interface examples doc tests

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
