# $Id: makefile,v 1.5 2003/02/27 17:54:11 flanigan Exp $


#DIRS     = src interface examples doc
LOCDIR    = src/Infrastructure/CommMem

include $(ESMF_DIR)/makefile

DIRS     = src interface examples 