# $Id: makefile,v 1.5 2003/04/15 22:34:36 lzaslavsky Exp $

LOCDIR    = src/Infrastructure/ConfigAttr

include $(ESMF_DIR)/makefile

DIRS      = src tests doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
