# $Id: makefile,v 1.6 2003/04/16 02:45:43 lzaslavsky Exp $

LOCDIR    = src/Infrastructure/ConfigAttr

include $(ESMF_DIR)/makefile

DIRS      =  src tests doc

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
