# $Id: makefile,v 1.18 2010/11/19 03:11:48 theurich Exp $ 


LOCDIR   = src

include $(ESMF_DIR)/makefile

DIRS        = prologue test_harness Infrastructure Superstructure epilogue \
              doc system_tests apps


CLEANFILES  = 
CLEANDIRS   = 
CLOBBERDIRS = 
MOSTLYCLEANDIRS = Infrastructure Superstructure system_tests test_harness


