# $Id: makefile,v 1.12 2006/02/14 18:27:51 svasquez Exp $ 


LOCDIR   = src

include $(ESMF_DIR)/makefile

DIRS        = prologue Infrastructure Superstructure epilogue \
              doc system_tests demo use_test_cases


CLEANFILES  = 
CLEANDIRS   = 
CLOBBERDIRS = 
DUSTDIRS    = Infrastructure Superstructure system_tests demo use_test_cases


