# $Id: makefile,v 1.5 2003/03/25 00:17:42 flanigan Exp $ 


LOCDIR   = src

include $(ESMF_DIR)/makefile

DIRS        = Infrastructure Superstructure doc SystemTests

CLEANDIRS   = 
CLOBBERDIRS = 
CLEANFILES  = 











