# $Id: makefile,v 1.1 2010/07/09 19:32:56 theurich Exp $ 

ALL: tree_build_apps

LOCDIR	  = src/apps/ESMC_Info


APPS_BUILD    = $(ESMF_APPSDIR)/ESMC_Info

APPS_OBJ      = ESMC_Info.o

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  = $(APPS_BUILD)
CLOBBERDIRS =

