# $Id: makefile,v 1.6 2008/09/26 05:53:53 cdeluca Exp $

ALL: build_here 

SOURCEC	  =  
SOURCEF	  =  ESMF_ArraySpec.F90
STOREH	  = 

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))

LIBBASE	  = libesmf
LOCDIR	  = src/Infrastructure/ArraySpec/src

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =

include $(ESMF_DIR)/makefile

DIRS	  = 

