# $Id$ 

ALL: tree_build_apps

LOCDIR	  = src/apps/ESMF_PrintInfo


APPS_BUILD    = $(ESMF_APPSDIR)/ESMF_PrintInfo

APPS_OBJ      = ESMF_PrintInfo.o

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  = $(APPS_BUILD)
CLOBBERDIRS =
