# $Id: makefile,v 1.2.2.2 2008/04/08 05:34:19 cdeluca Exp $ 

ALL: build_here 

SOURCEC	  = 
SOURCEF	  = ESMF_Attribute.F90
SOURCEH	  = 

OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))

MANSEC	  = Attrobj
LIBBASE	  = libesmf
DIRS	  = 
LOCDIR	  = src/Infrastructure/Attribute/src

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =






