# $Id: makefile,v 1.1 2009/03/18 05:50:31 eschwab Exp $

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Superstructure/IOAPI/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS      = interface tests

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =

