# $Id: makefile,v 1.1 2003/09/17 21:26:29 cdeluca Exp $ 


LOCDIR	  = src/Infrastructure/Bundle/

include $(ESMF_DIR)/makefile

DIRS	  = src interface examples doc tests

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


