# $Id: makefile,v 1.6 2007/10/10 18:20:55 feiliu Exp $ 

ALL: build_here

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/Bundle/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src interface doc tests examples
# TODO:FIELDINTEGRATION Restore Bundle tests and examples.

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


