# $Id: makefile,v 1.3 2004/08/04 20:52:18 nscollins Exp $

all: build_release

LOCDIR   = src/release

# destdir is relative to the release directory
RELEASE_DESTDIR = .
RELEASE_COPYFILES =
RELEASE_ARCHCOPYFILES = README

include $(ESMF_DIR)/makefile

DIRS     = example CoupledFlowSrc CoupledFlowExe lib mod include

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
