# $Id: makefile,v 1.2 2003/07/09 17:51:09 nscollins Exp $

all: build_release

LOCDIR   = src/release

# destdir is relative to the release directory
RELEASE_DESTDIR = .
RELEASE_COPYFILES =
RELEASE_ARCHCOPYFILES = README

include $(ESMF_DIR)/makefile

DIRS     = example CoupledFlowSrc CoupledFlowExe lib mod

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
