# $Id: makefile,v 1.2 2007/08/23 17:16:07 cdeluca Exp $

all: demos

LOCDIR   = src/demos

include $(ESMF_DIR)/makefile

DIRS     = 
# Disabled while putting new fields into grids.
# coupled_flow 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
