# $Id: makefile,v 1.3 2010/10/06 20:15:43 feiliu Exp $

all: demos

LOCDIR   = src/demos

include $(ESMF_DIR)/makefile

DIRS     =  coupled_flow
# Disabled while putting new fields into grids.
# coupled_flow 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
