name: Build ESMF Using Spack

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * MON'
    - cron: '0 0 * * FRI'

jobs:
  latest-stable:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        #os: [ubuntu-latest]
        os: [ubuntu-22.04]
        # available Intel oneAPI basekit, hpckit versions (as of 15-March-2023)
        # oneAPI: 2021.1.0, 2021.2.0, 2021.3.0, 2021.4.0, 2022.1.1, 2022.1.2, 2022.2.0, 2022.3.0, 2022.3.1, 2023.0.0 
        # available system provided GNU compiler versions
        # gnu  : 11.3.0
        #compiler: [oneapi@2023.0.0]
        compiler: [gcc@11.3.0]
        #esmf: [esmf@8.4.2, esmf@8.4.2~external-parallelio]
        #esmf: [esmf@8.4.2+parallelio~xerces~pnetcdf^parallelio@2.5.10+pnetcdf, esmf@8.4.2~xerces~pnetcdf]
        #esmf: [esmf@8.4.2+pio~parallelio~xerces~pnetcdf]
        #esmf: [esmf@8.4.2]
        esmf: [esmf@develop+external-parallelio+mpi~xerces^netcdf-c+dap+mpi^parallel-netcdf@1.12.3^parallelio@2.5.10+pnetcdf]

    steps:
    # check out base repo
    - name: Checkout Base Repository
      uses: actions/checkout@v3

    # prepare core environment
    - name: Install Core Development Tools
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install tar unzip file gringo
        sudo apt-get -qq install build-essential binutils-dev gfortran
        sudo apt-get -qq install python3-dev

    # restore Intel oneAPI compiler installation from cache
    - name: Restore Intel oneAPI Compiler Installation
      uses: actions/cache@v3
      if: ${{ startsWith(matrix.compiler, 'oneapi') }}
      with:
        path: /opt/intel/oneapi
        key: intel-${{ runner.os }}-${{ matrix.compiler }}
        restore-keys: |
          intel-${{ runner.os }}-${{ matrix.compiler }}

    # install compiler
    - name: Install Intel oneAPI Compiler
      if: ${{ startsWith(matrix.compiler, 'oneapi') }}
      run: |
        cd ${{ github.workspace }}/.github/workflows
        scripts/install_oneapi.sh -c ${{ matrix.compiler }}

    # concretize test environment 
    - name: Concretize Spack Environment Using YAML Specification
      run: |
        ${{ github.workspace }}/.github/workflows/scripts/spack_concretize.sh \
          -a x86_64 \
          -c ${{ matrix.compiler }} \
          -d ${{ matrix.esmf }} \
          -i ~/.spack-ci \
          -r ${{ github.workspace }} 

    # install test environment
    - name: Install ESMF with Spack 
      run: |
        ${{ github.workspace }}/.github/workflows/scripts/spack_install.sh \
          -r ${{ github.workspace }}

    # checkout NUOPC app prototypes
    - name: Checkout NUOPC app prototypes
      uses: actions/checkout@v3
      with:
        repository: esmf-org/nuopc-app-prototypes
        #repository: uturuncoglu/nuopc-app-prototypes
        path: ${{ github.workspace }}/nuopc-app-prototypes
        ref: develop

    # test installation using NUOPC app prototypes
    - name: Run NUOPC app prototypes
      run: |
        ${{ github.workspace }}/.github/workflows/scripts/run_nuopc_app_proto.sh \
          -c ${{ matrix.compiler }} \
          -r ${{ github.workspace }}/nuopc-app-prototypes \
          -s ~/.spack-ci
