name: Build ESMF Using Spack

on:
  workflow_dispatch:
  push:

jobs:
  latest-stable:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        # available compiler versions, as of 15-March-2023
        # intel: 2021.1.1, 2021.1.2, 2021.2.0, 2021.3.0, 2021.4.0, 2022.0.1, 2022.0.2, 2022.1.0, 2022.2.0, 2022.2.1, 2023.0.0
        # gnu  : 11.3.0
        #compiler: [gcc@11.3.0, oneapi@2022.0.2]
        compiler: [oneapi@2022.0.2]
        esmf: [esmf@8.4.1~pnetcdf, esmf@8.4.1~external-parallelio]

    steps:
    # check out base repo
    - name: Checkout Base Repository
      uses: actions/checkout@v3

    # prepare core environment
    - name: Install Core Development Tools
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install tar unzip file gringo
        sudo apt-get -qq install build-essential binutils-dev gfortran
        sudo apt-get -qq install python3-dev

    # restore dependencies from cache
    - name: Restore Dependencies
      uses: actions/cache@v3
      if: contains(${{ matrix.compiler }}, 'intel') || contains(${{ matrix.compiler }}, 'oneapi')
      with:
        path: /opt/intel/oneapi
        key: intel-${{ runner.os }}-${{ matrix.compiler }}
        restore-keys: |
          intel-${{ runner.os }}-${{ matrix.compiler }}

    # install compiler
    - name: Install Intel Compiler
      if: contains(${{ matrix.compiler }}, 'intel') || contains(${{ matrix.compiler }}, 'oneapi')
      run: |
        cd ${{ github.workspace }}/.github/workflows
        scripts/install_oneapi.sh -c ${{ matrix.compiler }}

    # concretize test environment 
    - name: Concretize Spack Environment Using YAML Specification
      run: |
        ${{ github.workspace }}/.github/workflows/scripts/spack_concretize.sh \
          -a x86_64 \
          -c ${{ matrix.compiler }} \
          -d ${{ matrix.esmf }} \
          -i ~/.spack-ci \
          -r ${{ github.workspace }} 

    # install test environment
    - name: Install Dependencies with Spack 
      run: |
        ${{ github.workspace }}/.github/workflows/scripts/spack_install.sh \
          -r ${{ github.workspace }}
