name: Build ESMF Using Spack

on:
  workflow_dispatch:
  push:

jobs:
  latest-stable:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [intel-oneapi-compilers@2023.0.0]
        esmf: [esmf@develop+parallelio~xerces~pnetcdf^parallelio@2.5.10]

    env:
      INTEL_INSTALL_DIR: /opt/intel/oneapi 

    steps:
    # check out base repo
    - name: Checkout Base Repository
      uses: actions/checkout@v3

    # prepare core environment
    - name: Install Core Development Tools
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install tar unzip file gringo
        sudo apt-get -qq install build-essential binutils-dev gfortran
        sudo apt-get -qq install python3-dev

    # concretize test environment 
    - name: Concretize Spack Environment Using YAML Specification
      run: |
        echo ${{ matrix.compiler }}
        echo ${{ matrix.esmf }}
        ${{ github.workspace }}/.github/workflows/scripts/spack_concretize.sh \
          -a x86_64 \
          -c ${{ matrix.compiler }} \
          -d ${{ matrix.esmf }} \
          -i ~/.spack-ci \
          -r ${{ github.workspace }} 

    # install test environment
    - name: Install Dependencies with Spack 
      run: |
        ${{ github.workspace }}/.github/workflows/scripts/spack_install.sh \
          -r ${{ github.workspace }}
