# $Id: makefile,v 1.2 2003/09/19 22:13:45 cdeluca Exp $

# This needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/LocalArray/

# Leave this line alone.
include $(ESMF_DIR)/makefile

# The DIRS line needs to contain all subdirectories which exist 
# directly below this directory, and have either library,
# example/test code, or documents which need to be generated.
DIRS	  = src interface tests

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
