# $Id: makefile,v 1.1 2003/09/18 15:57:06 cdeluca Exp $



# this needs to be the path of this directory relative to the
# top level esmf directory.
LOCDIR	  = src/Infrastructure/LocalArray/

include $(ESMF_DIR)/makefile

# the DIRS line needs to contain all subdirectories which exist 
#  directly below this directory, and have either library,
#  example/test code, or documents which need to be generated.
DIRS	  = src interface tests

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =
