#!/bin/csh -f
#
# Earth System Modeling Framework
# Copyright 2002-2003, University Corporation for Atmospheric Research, 
# Massachusetts Institute of Technology, Geophysical Fluid Dynamics 
# Laboratory, University of Michigan, National Centers for Environmental 
# Prediction, Los Alamos National Laboratory, Argonne National Laboratory, 
# NASA Goddard Space Flight Center.
# Licensed under the GPL.
#
# $Id: do_chprotex,v 1.2 2002/10/14 21:53:31 cdeluca Exp $
#
#===============================================================================
# chprotex
#===============================================================================
# 
# Process C++ include file prologue(s) using ProTex.
#
# Usage: co_chprotex <class> <c++ filename>
#
#        <class> is the name of the class whose definition/methods
#                are instrumented for ProTeX (e.g., ESMC_TimeInstant)
#
#        <C++_filename.h> is the name of the file that includes the 
#             prologue(s) instrumented for ProTeX (e.g., ESMC_TimeInstant.h)
#
# See the ProTeX documentation:
# http://dao.gsfc.nasa.gov/software/protex
# for a description of the command-line options used in this script.
# 
# E. Schwab                                                       Oct 11, 2002
#===============================================================================

if ($#argv != 2 ) then
  echo "Usage: chprotex <class> <C++_filename.h>"
  exit
else
  set class=$1
  set file=$2
  perl $DOC_DIR/templates/protex -bC +f $file > ${class}_chapi.tex
endif
