#!/bin/csh -f
#
# Earth System Modeling Framework
# Copyright 2002-2003, University Corporation for Atmospheric Research, 
# Massachusetts Institute of Technology, Geophysical Fluid Dynamics 
# Laboratory, University of Michigan, National Centers for Environmental 
# Prediction, Los Alamos National Laboratory, Argonne National Laboratory, 
# NASA Goddard Space Flight Center.
# Licensed under the GPL.
#
# $Id: do_fprotex,v 1.6 2003/03/20 20:32:37 flanigan Exp $
#
#===============================================================================
# do_fprotex
#===============================================================================
# 
# Process Fortran prologue(s) using ProTex.
#
# Usage: do_fprotex [-i] <class> <fortran filename>
#
#        [-i] is an optional argument to protex to cause non-printing of
#             BOPI -- EOPI internal prologues, which are intended for
#             Reference Manuals but not User Guides.
#
#        <class> is the name of the class or module whose functions
#               are instrumented for ProTeX (e.g., date)
#
#        <fortran_filename.F[90]> is the name of the file that includes the 
#               prologue(s) instrumented for ProTeX (e.g., date.F)
#
# See the ProTeX documentation:
# http://dao.gsfc.nasa.gov/software/protex
# for a description of the command-line options used in this script.
# 
# C. DeLuca                                                       March 15, 2001
#===============================================================================

if ($#argv < 2 ) then
  echo "Usage: do_fprotex [-i] <class> <fortran_filename.F[90]>"
  exit
else
  if ($#argv == 3 && $1 == '-i') then
    set option=$1
    set fnsuffix='fiapi.tex'
    shift
  else
    set option=''
    set fnsuffix='fapi.tex'
  endif
  set class=$1
  set file=$2
#  perl $DOC_DIR/templates/protex ${option} -bF +f $file > ${class}_${fnsuffix}
  perl $PROTEX ${option} -bF +f $file > ${class}_${fnsuffix}
endif

